// src/vue2/TodoItem.vue
<template>
  <div class="todo-item">
    <form class="todo-form" v-if="isEditing" @submit="editTodo">
      <input
        v-model="editingTitle"
        ref="editingTitleInput"
        type="text"
        name="title"
        placeholder="Todo title"
      />
      <button class="material-icons">check</button>
      <i class="material-icons" @click="onCancelEditing">
        close
      </i>
    </form>
    <div class="todo-view" v-else>
      <label>
        <input
          type="checkbox"
          :checked="isCompleted"
          @change="toggleCompleted"
        />
        <span>{{ title }}</span>
      </label>
      <i class="material-icons" @click="onEditing">
        edit
      </i>
      <i class="material-icons" @click="removeTodo">
        delete
      </i>
    </div>
  </div>
</template>

<script>
export default {
  props: ['id', 'title', 'isCompleted'],
  data: function() {
    return {
      isEditing: false,
      editingTitle: '',
    }
  },
  methods: {
    onEditing: function() {
      this.editingTitle = this.title
      this.isEditing = true
      this.$nextTick(() => this.$refs.editingTitleInput.focus())
    },
    onCancelEditing: function() {
      this.isEditing = false
    },
    editTodo: function(event) {
      event.preventDefault()
      store.editTodo(this.id, this.editingTitle)
      this.isEditing = false
    },
    removeTodo: function() {
      store.removeTodo(this.id)
    },
    toggleCompleted: function() {
      store.toggleCompleted(this.id)
    },
  },
}
</script>

// src/svelte/TodoItem.svelte
<script>
  import { tick } from 'svelte'

  export let id
  export let title
  export let isCompleted

  let isEditing = false
  let editingTitle = title
  let editingTitleInput

  async function onEditing() {
    editingTitle = title
    isEditing = true
    await tick()
    editingTitleInput.focus()
  }

  function onCancelEditing() {
    isEditing = false
  }

  function editTodo(event) {
    event.preventDefault()
    store.editTodo(id, editingTitle)
    isEditing = false
  }

  function removeTodo() {
    store.removeTodo(id)
  }

  function toggleCompleted() {
    store.toggleCompleted(id)
  }
</script>

<div class="todo-item">
  {#if isEditing}
    <form class="todo-form">
      <input
        bind:value={editingTitle}
        bind:this={editingTitleInput}
        type="text"
        name="title"
        placeholder="Todo title" />
      <button class="material-icons" on:click={editTodo}>check</button>
      <i class="material-icons" on:click={onCancelEditing}>close</i>
    </form>
  {:else}
    <div class="todo-view">
      <label>
        <input
          type="checkbox"
          bind:checked={isCompleted}
          on:change={toggleCompleted} />
        <span>{title}</span>
      </label>
      <i class="material-icons" on:click={onEditing}>edit</i>
      <i class="material-icons" on:click={removeTodo}>delete</i>
    </div>
  {/if}
</div>
