// src/react/TodoList.js
import React, { useState, useEffect } from 'react'
import TodoItem from './TodoItem'

const TodoList = () => {
  const [todos, setTodos] = useState(store.getTodos())

  const onAddTodo = (event) => {
    event.preventDefault()
    store.addTodo(event.target.elements.title.value)
    event.currentTarget.reset()
  }

  useEffect(() => {
    store.subscribeTodos((state) => setTodos(state))
  }, [])

  return (
    <div className='card'>
      <h5 className='section center-align white-text'>React</h5>
      <div className='card-content'>
        <form className='add-form row valign-wrapper' onSubmit={onAddTodo}>
          <div className='input-field col s9'>
            <input type='text' name='title' placeholder='Add todo' />
          </div>
          <button className='col s3 btn'>Add</button>
        </form>
        <div className='todo-items'>
          {todos.map((todo) => (
            <TodoItem key={store.getTodoKey(todo)} {...todo} />
          ))}
        </div>
      </div>
    </div>
  )
}

export default TodoList

// src/svelte/TodoList.svelte
<script>
  import { onMount } from 'svelte'
  import TodoItem from './TodoItem.svelte'

  let todos = store.getTodos()

  onMount(() => {
    store.subscribeTodos((state) => {
      todos = state
    })
  })

  function getTodoKey(todo) {
    return store.getTodoKey(todo)
  }

  function addTodo(event) {
    event.preventDefault()
    store.addTodo(event.target.elements.title.value)
    event.currentTarget.reset()
  }
</script>

<div class="card">
  <h5 class="section center-align white-text">Svelte</h5>
  <div class="card-content">
    <form class="add-form row valign-wrapper" on:submit={addTodo}>
      <div class="input-field col s9">
        <input type="text" name="title" placeholder="Add todo" />
      </div>
      <button class="col s3 btn">Add</button>
    </form>
    <div class="todo-items">
      {#each todos as todo (getTodoKey(todo))}
        <TodoItem {...todo} />
      {/each}
    </div>
  </div>
</div>
